In [2]:
import pandas as pd

In [5]:
CODE_RUN = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\TRASH\itresume-coderun.csv', sep=',')

# 1. Случайная выборка

In [10]:
random_sampling = CODE_RUN.sample(n = 10000)
random_sampling.head(5)

          id               created_at  problem_id  user_id  language_id
42011  42012  2022-04-05 15:07:45.121          77     2524            2
43086  43087  2022-04-08 15:18:40.298         221     2604            3
29191  29192  2022-02-21 08:33:26.861          91     1820            2
1947    1948  2021-11-26 05:21:05.902          69      237            2
23255  23256  2022-02-11 16:35:41.080         142     1090            2

In [11]:
replace_random_sampling = CODE_RUN.sample(n = 10000, replace = True)
replace_random_sampling.head(5)

          id               created_at  problem_id  user_id  language_id
12288  12289  2022-01-18 08:23:14.888          70      342            2
16143  16144  2022-01-25 18:28:29.343          81      614            2
30311  30312  2022-02-23 12:36:41.263          69     1907            2
47184  47185  2022-04-18 06:48:17.215         192     2604            3
50292  50293  2022-04-25 12:47:17.398         151     2733            2

In [12]:
frac_random_sampling = CODE_RUN.sample(frac = 0.25)
frac_random_sampling.head(5)

          id               created_at  problem_id  user_id  language_id
42864  42865  2022-04-07 18:16:57.676          99     2524            2
432      433  2021-09-21 08:18:25.988         111       63            3
24053  24054  2022-02-12 20:28:03.442         151      218            2
43475  43476  2022-04-10 06:08:46.778          88     2524            2
22588  22589  2022-02-10 08:41:02.602         135     1090            2

# 2. Механическая выборка

In [14]:
# Здесь нам нужно как-то упорядочить элементы. Мы не будем сортировать датафрейм CODE_RUN. Но при необходимости упорядочить датафрейм можно с помощью функции:
# df.sort_values(by, ascending)

In [15]:
# Далее нужно выбрать шаг, с которым будем выбирать элементы h и номер первого элемента k. И используем функцию: df.iloc[k::h]

In [16]:
#Выбираем каждый пятый элемент, начиная с нулевого
sys_sample_0_5 = CODE_RUN.iloc[::5]

#Выбираем каждый пятый элемент, начиная с третьего
sys_sample_3_5 = CODE_RUN.iloc[3::5]
sys_sample_3_5.head(5)

    id               created_at  problem_id  user_id  language_id
3    4  2021-03-29 21:24:51.000          26        4            3
8    9  2021-04-06 12:14:59.000          24        1            3
13  14  2021-03-31 14:10:57.000          14        3            3
18  19  2021-04-04 18:18:35.000          27        9            3
23  24  2021-03-27 17:55:11.000          13       20            3

# 3. Стратифицированная выборка

In [17]:
# Чтобы сделать стратифицированную выборку, сгруппируем набор данных по столбцу 'col_name' и выберем случайным образом n строк из каждой группы. 

# При такой выборке мы не можем гарантировать, что в группе будет n уникальных строк, поэтому либо нужно добавить параметр replace = True, 
# тогда выборка будет повторная, либо заранее оценить самую малочисленную группу и поставить n равный или меньше найденного значения.

In [20]:
stratified_sample = CODE_RUN.groupby('problem_id', group_keys=False).apply(lambda x: x.sample(n = 3, replace = True))
stratified_sample.head(5)

          id               created_at  problem_id  user_id  language_id
4313    4314  2021-12-05 18:57:18.423           1      291            3
333      334  2021-09-20 00:27:10.435           1       43            3
369      370  2021-09-20 13:04:06.065           1       63            3
40015  40016  2022-03-30 13:22:03.661           2     2509            3
40015  40016  2022-03-30 13:22:03.661           2     2509            3

In [19]:
# При таком выборе мы добавляем в выборку равное количество экземпляров из каждой группы, что не совсем правильно.

# Предположим, мы оцениваем среднее число покупок в магазине косметики и решили сделать стратифицированную выборку. 
#В базе клиентов 90 девушек и 10 мужчин. Когда мы будем делать выборку приведенным выше способом, например, поставим n=10, то получим 10 мужчин и 10 женщин.
# Женщины покупают косметику с завидной регулярностью, а вот мужчины от силы 3 раза в год: день рождения жены, Новый год и 8 марта.
# В итоге мы получим выборку с равной пропорцией элементов из каждой группы, хотя в ГС мы видим, что одна группа в 9 раз больше другой. 
# И если по данной выборке мы будем делать заключение о всей ГС, то получим искаженный результат.

# Что же делать?

# Мы можем добавить параметр frac. Тогда из каждой группы мы возьмем равную часть от каждой группы. Например, frac=0.5 – это 50% от группы.

In [22]:
stratified_sample = CODE_RUN.groupby('problem_id', group_keys=False).apply(lambda x: x.sample(frac=0.5))
stratified_sample.head(5)

          id               created_at  problem_id  user_id  language_id
27639  27640  2022-02-18 06:44:20.424           1     1622            3
33289  33290  2022-03-09 13:07:31.922           1     1544            3
39995  39996  2022-03-30 12:55:58.695           1     2509            3
1462    1463  2021-11-24 03:45:27.657           1      105            3
6205    6206  2021-12-17 10:40:17.223           1      347            3