In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('/Users/vladislavlipkin/Downloads/data_work.xlsx', sheet_name = 'exportSD')

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [8]:
df.columns

Index(['Дата/время регистрации', ' ', 'Номер', 'Статус', 'Приоритет',
       'Получатель услуг', 'Инициатор', 'Расположение', 'Описание',
       'Фактическое время выполнения', '     Услуга', '    Компонент услуги',
       '   Вид запроса', 'Площадка обслуживания пользователя',
       'Техническое описание', 'Головной запрос', '  Конфигурационные единицы',
       'Текущий ответственный', 'Кем решен (сотрудник)',
       'Кто выполняет контроль? (Сотрудник)', 'Плановое время выполнения',
       'Просрочен', '     Результат работ', '     Описание решения',
       'Количество уточнений', 'Количество возобновлений',
       'Качество проведения работ по Запросу',
       'Статус исполнения дочерних запросов', 'Крайний срок обработки',
       'Крайний срок обработки ТО', 'Отложенный запрос',
       'Время входа в статус'],
      dtype='object')

In [5]:
df.head(1)

,Дата/время регистрации,,Номер,Статус,Приоритет,Получатель услуг,Инициатор,Расположение,Описание,Фактическое время выполнения,...,Результат работ,Описание решения,Количество уточнений,Количество возобновлений,Качество проведения работ по Запросу,Статус исполнения дочерних запросов,Крайний срок обработки,Крайний срок обработки ТО,Отложенный запрос,Время входа в статус
0,2020-07-29 16:57:41.315,Запрос на обслуживание,RP2634178,Закрыт,(4) Низкий,Парменов Сергей Анатольевич,Парменов Сергей Анатольевич,ПАТЭС Спб,Обновление антивирусных баз Добрый день. Прошу...,2020-07-30 08:56:31.214,...,Решение предоставлено,Уважаемый Сергей Анатольевич! Ваша заявка была...,0,0,0,NaN,2020-08-17 11:27:50.526,NaN,NaN,2020-08-06 09:00:09.198

In [20]:
df.loc[:,['Дата/время регистрации', 'Крайний срок обработки', 'Фактическое время выполнения', 'Плановое время выполнения', 'Приоритет', 'Просрочен', '     Результат работ', 'Получатель услуг', 'Инициатор', 'Кем решен (сотрудник)', 'Расположение', 'Описание', '     Услуга', '    Компонент услуги', '   Вид запроса', 'Площадка обслуживания пользователя']].head(5)

,Дата/время регистрации,Крайний срок обработки,Фактическое время выполнения,Плановое время выполнения,Приоритет,Просрочен,Результат работ,Получатель услуг,Инициатор,Кем решен (сотрудник),Расположение,Описание,Услуга,Компонент услуги,Вид запроса,Площадка обслуживания пользователя
0,2020-07-29 16:57:41.315,2020-08-17 11:27:50.526,2020-07-30 08:56:31.214,2020-08-10 11:27:41.315,(4) Низкий,не просрочен,Решение предоставлено,Парменов Сергей Анатольевич,Парменов Сергей Анатольевич,Аширов Юрий Алексеевич,ПАТЭС Спб,Обновление антивирусных баз Добрый день. Прошу...,ИТ-АРМ,ИТ-14-7-1 Автоматизированное рабочее место с о...,4. Настройка / обновление ПО,Плавучая атомная теплоэлектростанция
1,2020-09-03 17:12:25.514,2020-09-22 11:48:43.947,2020-09-04 10:37:38.608,2020-09-15 11:00:00.000,(4) Низкий,не просрочен,Решение предоставлено,Глушкова Наталья Александровна,Глушкова Наталья Александровна,Катанов Антон Сергеевич,Ленинградская АЭС,"Портал: Заявка на доступ к ИС ""Организация раб...",ИТ-АРМ,ИТ-14-7 Программная поддержка рабочего места н...,Запрос на обслуживание,Ленинградская АЭС
2,2020-12-24 11:10:54.874,2021-01-15 15:28:52.818,2020-12-24 16:23:14.968,2020-12-31 15:25:54.874,(4) Низкий,не просрочен,Решение предоставлено,Яцына Светлана Александровна,Коротицкий Николай Анатольевич,Коротицкий Николай Анатольевич,Ленинградская АЭС-2,"Проверить клиент Horizon, настроить почтовый к...",ИТ-АРМ,ИТ-14-37 Программная поддержка рабочего места ...,Настройка / обновление ПО,Ленинградская АЭС-2
3,2021-02-12 15:05:12.186,2021-03-05 09:37:28.359,2021-02-12 15:23:53.645,2021-02-26 09:35:12.186,(4) Низкий,не просрочен,Решение предоставлено,Мосалева Елена Алексеевна,Мосалева Елена Алексеевна,Аширов Юрий Алексеевич,ПАТЭС Спб,Настроить CheckPoint VPN.,ИТ-АРМ,ИТ-14-7-1 Автоматизированное рабочее место с о...,4. Настройка / обновление ПО,Плавучая атомная теплоэлектростанция
4,2021-02-11 08:40:34.669,2021-02-25 12:59:19.790,2021-02-15 11:15:40.259,2021-02-16 15:15:00.000,(4) Низкий,не просрочен,Отменен,Щербаков Анатолий Максимович,Щербаков Анатолий Максимович,Струсинский Павел Михайлович,ЦА Москва,срочно!!! Прошу обеспечить доступ к оперативно...,ИТ-Система КЦ,ИТ-11-9-1 Программный комплекс представления в...,Запрос на обслуживание,Ленинградская АЭС

In [9]:
for col_name in df.columns:
    print(col_name)

Дата/время регистрации

Номер
Статус
Приоритет
Получатель услуг
Инициатор
Расположение
Описание
Фактическое время выполнения
     Услуга
    Компонент услуги
   Вид запроса
Площадка обслуживания пользователя
Техническое описание
Головной запрос
  Конфигурационные единицы
Текущий ответственный
Кем решен (сотрудник)
Кто выполняет контроль? (Сотрудник)
Плановое время выполнения
Просрочен
     Результат работ
     Описание решения
Количество уточнений
Количество возобновлений
Качество проведения работ по Запросу
Статус исполнения дочерних запросов
Крайний срок обработки
Крайний срок обработки ТО
Отложенный запрос
Время входа в статус

In [7]:
df?

Type:        DataFrame
String form:
Дата/время регистрации                              Номер  \
           0     2020-07-29 16:57:41.315 <...>                        NaN               NaN 2025-11-18 09:54:04.972

           [18992 rows x 32 columns]
Length:      18992
File:        /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/frame.py
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3